name: JupyterViz
version: 1.5.5
date: 2022-05-08
description: |
    Visualization Tools for Jupyter and the GAP REPL

authors:
    - name: Nathan Carter
      url: http://nathancarter.github.io

maintainers:
    - name: Nathan Carter
      url: http://nathancarter.github.io

GAP: ">= 4.9"

needed-pkgs:
    - name: "json"
      version: "2.0.0"
      url: "https://gap-packages.github.io/json/"
    - name: "GAPDoc"
      version: "1.3"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://nathancarter.github.io/jupyterviz
readme: README.md
packageinfo: https://nathancarter.github.io/jupyterviz/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/nathancarter/jupyterviz/releases/download/v1.5.5/jupyterviz-1.5.5.tar.gz

abstract: |
    The <span class="pkgname">JupyterViz</span> package    adds visualization tools for use in Jupyter Notebooks    or from the GAP REPL.  Those tools can be used to make    charts, graphs, and arbitrary other visualizations.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Jupyter Notebook, visualization, graph, plot, chart, HTML, JavaScript.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Car22</span>]   <b class='BibAuthor'>Carter, N.</b>,
     <i class='BibTitle'>JupyterViz, Visualization Tools for Jupyter and the GAP REPL,
             Version 1.5.5</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://nathancarter.github.io/jupyterviz">https://nathancarter.github.io/jupyterviz</a></span>.
    </p>
    

bibtex: |
    @misc{ JupyterViz1.5.5,
      author =           {Carter, N.},
      title =            {{JupyterViz},  Visualization Tools for Jupyter and the
                          GAP REPL, {V}ersion 1.5.5},
      month =            {May},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href      {https://nathancarter.github.io/jupyterviz}
                          {\texttt{https://nathancarter.github.io/}\discretionary
                          {}{}{}\texttt{jupyterviz}}},
      keywords =         {Jupyter  Notebook;  visualization; graph; plot; chart;
                          HTML; JavaScript},
      printedkey =       {Car22}
    }

